language: python

python:
  - '3.6'

dist: xenial
sudo: required

before_install:
  - echo     "deb https://deb.torproject.org/torproject.org xenial main"                    | sudo tee -a /etc/apt/sources.list.d/torproject.list
  - echo "deb-src https://deb.torproject.org/torproject.org xenial main"                    | sudo tee -a /etc/apt/sources.list.d/torproject.list
  - echo     "deb https://deb.torproject.org/torproject.org tor-nightly-master-xenial main" | sudo tee -a /etc/apt/sources.list.d/torproject.list
  - echo "deb-src https://deb.torproject.org/torproject.org tor-nightly-master-xenial main" | sudo tee -a /etc/apt/sources.list.d/torproject.list
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
  - gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
  - sudo apt update
  - sudo apt install python3-setuptools python3-tk tor -y
  - export TZ=Europe/Helsinki

install:
  - pip install pytest pytest-cov pyyaml coveralls
  - pip install -r requirements.txt       --require-hashes
  - pip install -r requirements-relay.txt --require-hashes

script:
  - py.test --cov=src tests/

after_success:
  - coveralls
